# Generated by Django 2.2.7 on 2019-12-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191204_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_at',
            field=models.DateField(),
        ),
    ]
